name: Build FaceApp APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            build-essential \
            ccache \
            git \
            zip \
            unzip \
            openjdk-17-jdk \
            python3-pip \
            pkg-config \
            libffi-dev \
            libssl-dev \
            autoconf \
            automake \
            libtool \
            zlib1g-dev \
            libncurses5-dev \
            libncursesw5-dev \
            libtinfo-dev

      - name: Upgrade pip and install Cython
        run: |
          pip install --upgrade pip virtualenv
          pip install --upgrade Cython==0.29.33

      - name: Install Buildozer, Kivy, garden CLI and project requirements
        env:
          PIP_BREAK_SYSTEM_PACKAGES: "0"
        run: |
          pip install kivy==2.3.0 buildozer==1.5.0 requests==2.31.0
          pip install kivy-garden
          pip install -r requirements.txt

      - name: Ensure ~/.local/bin is on PATH
        run: echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Fix garden CLI permissions
        run: |
          if [ -f "$HOME/.local/bin/garden" ]; then
            chmod +x "$HOME/.local/bin/garden"
          fi

      - name: Install Android WebView garden package
        run: |
          ~/.local/bin/garden install android_webview --app

      - name: Build the APK with Buildozer
        run: |
          buildozer --verbose android debug

      - name: Upload built APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: faceapp-apk
          path: ./bin/*.apk
